apiVersion: v1
kind: Service
metadata:
  name: branch-filter
  namespace: tekton-pipelines
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: branch-filter
  sessionAffinity: None
  type: ClusterIP
